#!/usr/bin/env bash
#
# Copyright 2016 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o nounset \
    -o errexit \
    -o verbose \
    -o xtrace

echo "===> ENV Variables ..."
env | sort

echo "===> User"
id

echo "===> Iniatializing Zookeeper Host..."
if [[ -z "${KAFKA_LISTENERS-}" ]]
then
        zkhosts=$(awk '{print $2}' /tmp/zookeepers)
        if [ -n "$zkhosts" ] ; then
                zknodes=`echo $zkhosts`                 # convert <\n> to ' '
        fi
        export ZOOKEEPER_PORT=${ZOOKEEPER_PORT:-"2181"}
        for znode in ${zknodes//,/ } ; do
                zk+=$znode:$ZOOKEEPER_PORT,
        done
        export KAFKA_ZOOKEEPER_CONNECT=${zk::-1}
fi
echo $KAFKA_ZOOKEEPER_CONNECT



echo "===> Iniatializing Broker Host..."
if [[ -z "${KAFKA_ADVERTISED_LISTENERS-}" ]]
then
        murl_top=http://169.254.169.254/latest/meta-data
        ThisInstance=$(curl -f $murl_top/instance-id 2> /dev/null)
        ThisRegion=$(curl -f $murl_top/placement/availability-zone |sed 's/[a-z]$//')
        ThisPrivateIpAddress=$(curl -f $murl_top/local-ipv4)

        LISTENERS=${LISTENERS:-"PLAINTEXT://:9092"}
        echo ${LISTENERS//,/ }
        for bnode in ${LISTENERS//,/ } ; do
        brListeners+=${bnode///://$ThisPrivateIpAddress:},
        done
        export KAFKA_ADVERTISED_LISTENERS=${brListeners::-1}
fi
echo $KAFKA_ADVERTISED_LISTENERS

echo "===> Iniatializing JMX Host..."
if [[ -z "${KAFKA_JMX_HOSTNAME-}" ]]
then
        export KAFKA_JMX_HOSTNAME=${KAFKA_JMX_HOSTNAME:-$ThisPrivateIpAddress}
fi
echo $KAFKA_JMX_HOSTNAME

echo "===> Configuring ..."
/etc/confluent/docker/configure

echo "===> Running preflight checks ... "
/etc/confluent/docker/ensure

echo "===> Launching ... "
exec /etc/confluent/docker/launch
