FROM 192491131326.dkr.ecr.us-east-1.amazonaws.com/infra/kafka:0.10.0.1

ARG COMMIT_ID=unknown
LABEL io.confluent.docker.git.id=$COMMIT_ID
ARG BUILD_NUMBER=-1
LABEL io.confluent.docker.build.number=$BUILD_NUMBER

MAINTAINER irfan.prasla@infor.com
LABEL io.confluent.docker=true

ENV COMPONENT=kafka

# primary
EXPOSE 9092
ENV KAFKA_VERSION="0.10.0.1"

COPY include/etc/confluent/docker /etc/confluent/docker

CMD ["/etc/confluent/docker/run"]
